# 日志参数
log:
  sink: './log/{time}.log'              # 日志目录
  rotation: '00:00'                     # 日志文件重建时间
  retention: '3 months'                 # 定期清理间隔
  compression: 'zip'                    # 日志文件压缩格式
# torch-serve参数
ts:
  det_model: 'dbnet'                    # 检测模型
  recog_model: 'sar_cn'                 # 识别模型
  inference_addr: '192.168.1.10:8080'   # 服务地址
# 滑窗推理参数
infer:
  slice_height: 736                     # 窗口高度
  slice_width: 1333                     # 窗口宽度
  slice_height_overlap: 0.1             # 窗口y方向重叠率
  slice_width_overlap: 0.1              # 窗口x方向重叠率
  threshold_det: 0.8                    # 检测阈值
  threshold_recog: 0.8                  # 识别阈值
# 输入输出
io:
  input_folder: 'data/infer_in'         # 输入文件夹
  output_folder: 'data/infer_out'       # 输出文件夹